# Schema for the configuration files of the Admin CSS module.

admincss.settings:
  type: config_object
  label: 'Admin CSS settings'
  mapping:
    custom_css:
      type: string
      label: 'Custom CSS'
